#################################################################################################################
#image: docker
image: n/a

#################################################################################################################
before_script:
  - echo "this is the before_script in action - will install frameworks' plugins"
  - npm install
  - echo


#################################################################################################################
stages:
  - add_creation_script_run   #run the add creation script
  - docker_build_and_push     #stage for re-building & pushing the docker image --- THIS STAGE IS NOT WORKING YET - NEEDS TO BE CREATED & TESTED


#################################################################################################################
CreateNewListings:
  image: git@gitlab.com:3learner/hpcl.git # git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing
  stage: add_creation_script_run
  script:
    - echo "automated test run -------------------------------------------------------------------------------------"
    - npm run CreateNewListings -- --role=craigListUser --env=tst --appName=craigListVan --browserStack=true --timeout=350000
    - echo

  when: manual
  allow_failure: false

  only:
    - master

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: http://.webxmedia.ca



#################################################################################################################
1.Build_Docker_Image:
  stage: docker_build_and_push
  script:
    - echo "build docker image if automated tests are passed -------------------------------------------------------"
    - echo "nothing yet - not done"
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker info
#    - docker build --no-cache -t git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing:latest .
#    - if [ -n "${UPLOAD_TO_S3}" ]; then make upload; fi
    - echo

  when: manual
  allow_failure: false

  only:
    - master

#################################################################################################################
2.Push_Docker_Image:
  stage: docker_build_and_push
  script:
    - echo "push docker image if docker image was built ------------------------------------------------------------"
    - echo "nothing yet - not done"
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#    - docker push git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing:latest .
#    - if [ -n "${Build_Docker_Image}" ]; then make upload; fi
    - echo

  when: manual
  allow_failure: false

  only:
    - master

#################################################################################################################
3.Docker_Image_Test:
  stage: docker_build_and_push
  script:
    - echo "run a small test to check the build docker image works -------------------------------------------------"
    - npm run generic:ValidateInternalMenuAsContentEditor -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master


#################################################################################################################



after_script:
  - echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ tests run done ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"